services:
  gateway:
    image: nginx:1.27-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build: .
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/flash_sale
      REDIS_URL: redis://redis:6379
      DB_POOL_SIZE: 12
      CACHE_TTL_SECONDS: 5
      ORDER_QUEUE_NAME: orders:pending
      MAX_QUEUE_DEPTH: 2000
      RATE_LIMIT_PER_SECOND: 500
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: npm run worker
    environment:
      WORKER_METRICS_PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/flash_sale
      REDIS_URL: redis://redis:6379
      ORDER_QUEUE_NAME: orders:pending
      WORKER_DB_POOL_SIZE: 8
      WORKER_MAX_ATTEMPTS: 3
    expose:
      - "3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash_sale
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flash_sale"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  prometheus:
    image: prom/prometheus:v2.53.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: light
    ports:
      - "3100:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
